[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
grass = { version = "0.12.4", default-features = false, features = ["random"] }
jotdown = "0.3.0"
md5 = "0.7.0"
minijinja = { version = "1.0.3", features = ["loader", "speedups"] }
once_cell = "1.18.0"
serde = { version = "1.0.166", features = ["derive"] }
toml = "0.7.6"
walkdir = "2.3.3"
