[package]
edition = "2018"
name = "web"
version = "0.1.0"

[dependencies]
anyhow = "1.0.44"
askama = "0.10.5"
axum = "0.2.8"
minify-html = "0.6.8"
once_cell = "1.8.0"
tokio = { version = "1.12.0", features = ["full"] }
tower = { version = "0.4.9", features = ["util", "timeout"] }
tower-http = { version = "0.1.1", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = "0.2.25"
