[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
brotli = "3.3.4"
flate2 = "1.0.26"
grass = { version = "0.12.4", default-features = false, features = ["random"] }
jotdown = "0.3.0"
md5 = "0.7.0"
minijinja = { version = "1.0.3", features = ["loader", "speedups"] }
once_cell = "1.18.0"
quick-xml = { version = "0.29.0", features = ["serialize"] }
serde = { version = "1.0.166", features = ["derive"] }
time = { version = "0.3.22", features = ["serde-human-readable"] }
toml = "0.7.6"
url = { version = "2.4.0", features = ["serde"] }
walkdir = "2.3.3"
