[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["ws"] }
brotli = "3.3.4"
flate2 = "1.0.26"
grass = { version = "0.13.0", default-features = false }
jotdown = "0.3.0"
lightningcss = { version = "1.0.0-alpha.44", default-features = false, features = ["browserslist", "grid"] }
md5 = "0.7.0"
minify-html = "0.11.1"
minijinja = { version = "1.0.4", features = ["loader", "speedups"] }
minijinja-autoreload = "1.0.4"
notify = "6.0.1"
once_cell = "1.18.0"
quick-xml = { version = "0.29.0", features = ["serialize"] }
serde = { version = "1.0.166", features = ["derive"] }
time = { version = "0.3.22", features = ["serde-human-readable"] }
tokio = { version = "1.29.1", features = ["full"] }
toml = "0.7.6"
tower-http = { version = "0.4.1", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = { version = "2.4.0", features = ["serde"] }
walkdir = "2.3.3"
